FROM registry.cn-hangzhou.aliyuncs.com/k1s/openjdk11
EXPOSE 9020
ENV url=http://127.0.0.1:9020/ews/cfc/nacos/register
WORKDIR /ems
COPY target/configuration-center-1.0-SNAPSHOT.jar  configuration-center.jar
ENV JAVA_OPTS="-XX:OnOutOfMemoryError=/script/ding.sh -XX:+HeapDumpOnOutOfMemoryError -XX:ErrorFile=/opt/hs_err_pid_%p.log -XX:HeapDumpPath=/opt/java.hprof
-XX:+UseContainerSupport -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
-Xlog:gc*=debug:file=/opt/java-gc.log:utctime,level,tags:filecount=10,filesize=100M
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000 -Duser.timezone=GMT+08"
ENV APM="-javaagent:agent/skywalking-agent.jar -Dskywalking.agent.service_name=configuration-center -Dskywalking.collector.backend_service=10.44.3.229:11800"
ENTRYPOINT java  ${JAVA_OPTS} ${APM} -jar *.jar --spring.profiles.active=prod


prd参数预览
-XX:OnOutOfMemoryError=/script/ding.sh
-XX:+HeapDumpOnOutOfMemoryError
-XX:ErrorFile=/opt/hs_err_pid_%p.log
-XX:HeapDumpPath=/opt/java.hprof
-XX:+UseContainerSupport
-XX:InitialRAMPercentage=50.0
-XX:MaxRAMPercentage=75.0
-XX:+UseG1GC
-Xlog:gc*=debug:file=/opt/java-gc.log:utctime,level,tags:filecount=10,filesize=100M
-Xdebug
-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000 -Duser.timezone=GMT+08



完整配置参见: https://www.cnblogs.com/zkyefei/p/9334562.html






